import React from 'react';
import {
  File, Folder, FolderOpen, Settings, MessageSquare, Play,
  Search, X, Plus, ChevronRight, ChevronDown, ChevronUp, ChevronLeft, Save,
  Trash2, Upload, Download, RefreshCw, Wand2, Check, CheckCheck, Copy, Monitor,
  Image as ImageIcon, FileCode, FileText, LayoutTemplate,
  Code, GitBranch, AlertCircle, AlertTriangle, Files, FolderPlus, Brain,
  Terminal, Info, Bell, ExternalLink, Globe, HardDrive, PanelLeft,
  Eye, EyeOff, FilePenLine, FilePlus, Paperclip, Send, Square,
  FileMinus, Cpu, Zap, BookOpen
} from 'lucide-react';

export const Icons = {
  File,
  Folder,
  FolderOpen,
  FolderPlus,
  Settings,
  MessageSquare,
  Play,
  Search,
  X,
  Plus,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  Save,
  Trash2,
  Upload,
  Download,
  RefreshCw,
  Wand2,
  Check,
  CheckCheck,
  Copy,
  Monitor,
  Image: ImageIcon,
  FileCode,
  FileText,
  FilePenLine,
  FilePlus,
  FileMinus,
  LayoutTemplate,
  PanelLeft,
  Code,
  GitBranch,
  AlertCircle,
  AlertTriangle,
  Files,
  Brain,
  Terminal,
  Info,
  Bell,
  ExternalLink,
  Globe,
  HardDrive,
  Eye,
  EyeOff,
  Paperclip,
  Send,
  Square,
  Cpu,
  Zap,
  BookOpen,
};

export default Icons;
